#A* -------------------------------------------------------------------
#B* This file contains source code for running a GitHub automation
#-* related to the build process of the PyMOL computer program
#C* Copyright 2025 by Martin Urban.
#D* -------------------------------------------------------------------
#E* It is unlawful to modify or remove this copyright notice.
#F* -------------------------------------------------------------------
#G* Please see the accompanying LICENSE file for further information.
#H* -------------------------------------------------------------------
#I* Additional authors of this source file include:
#-*
#-*
#-*
#Z* -------------------------------------------------------------------
name: Build App Package

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-13
            arch: x64
          - os: macos-14
            arch: arm64
        python-version: ["3.11"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install wheel setuptools  # setuptools needed for Python >=3.12
          python -m pip install -r requirements.txt
          python -m pip install pyqt5

      - name: Build app package
        run: |
          source .venv/bin/activate
          python automations/my_automator.py setup dev-env
          pip install pre-built/wheel/${{ matrix.arch }}/pymol-3.1.0a0-py3-none-any.whl
          python automations/my_automator.py build app
          python automations/my_automator.py build dmg

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS_PyMOL-exe-${{ matrix.os }}-${{ matrix.arch }}
          path: dist/*
