#A* -------------------------------------------------------------------
#B* This file contains source code for running a GitHub automation
#-* related to the build process of the PyMOL computer program
#C* Copyright 2025 by Martin Urban.
#D* -------------------------------------------------------------------
#E* It is unlawful to modify or remove this copyright notice.
#F* -------------------------------------------------------------------
#G* Please see the accompanying LICENSE file for further information.
#H* -------------------------------------------------------------------
#I* Additional authors of this source file include:
#-*
#-*
#-*
#Z* -------------------------------------------------------------------
name: Build App Package for arm64 arch

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-14
            arch: arm64
        python-version: ["3.11"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install wheel setuptools  # setuptools needed for Python >=3.12
          python -m pip install -r requirements.txt
          python -m pip install pyqt5

      - name: Build app package
        run: |
          source .venv/bin/activate
          python automations/my_automator.py setup dev-env
          pip install pre-built/wheel/${{ matrix.arch }}/pymol-*-py3-none-any.whl
          python automations/my_automator.py build app
      - name: Rename app package
        run: mv dist/open_source_pymol-3.1.0a0.app dist/Open-Source-PyMOL-3.1.0a0.app
      - name: Setup NodeJS
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.2/install.sh | bash
          \. "$HOME/.nvm/nvm.sh"
          nvm install 18

      - name: Build DMG
        run: |
          npm install --global create-dmg
          create-dmg 'dist/Open-Source-PyMOL-3.1.0a0.app'
#      - name: Build DMG
#        uses: urban233/create-dmg-actions@v0.0.2
#        with:
#          dmg_name: 'Open-Source-PyMOL'
#          src_dir: 'dist/Open-Source-PyMOL-3.1.0a0.app'
#          bg_filepath: 'alternative_design/dmg_bg.png'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS_PyMOL-DMG-${{ matrix.os }}-${{ matrix.arch }}
          path: ./*.dmg
